### ISSUE TITLE
Switch between higher and lower than current

### ISSUE THREAD

**Issue by supernoir** [supernoir/binary-search-game#1]
I want the loop to change according to the user input. User input works, the loop works for higher than, but not for lower than (user input up rather than user input down). As lower than works in principle, I then need to turn around the calculation of current, but my mind is just blurry at the moment... @stefanwille can you give me a hint?

**Comment by stefanwille** [comment]
Your are working on the file binarysearchgame_01.rb right?

I spot two problems:
1. The function `less_more_equal` expect three parameters `(less,more,equal)` but when you call the method, you dont' pass any - this can't work. The function doesn't need parameters for what you want it to do - just ditch the parameters from the function declaration.
2. In line 93 you expect the function `less_more_equal` to return a value, but you never return that value in the function's implementation. Make sure that at the end of the function you have an expression that is evaluates either to `true` or `false`, according to the user input.

The details I leave to you as an exercise :smile: Ask me again if you really get stuck.

**Comment by supernoir** [comment]
@stefanwille Solved it, but it ain't pretty (yet!)

**Comment by stefanwille** [comment]
Yes, that's it - great! :smile:
