### ISSUE TITLE
Migration from ruby to angularjs (rather than ruby/sinatra + js)

### ISSUE THREAD

**Issue by supernoir** [supernoir/binary-search-game#2]
The idea being that it can be an application that runs entirely in the front end, with each part of the game using their own route, and each step of the game being rendered ad hoc on the same page in a subsequent cell.

@stefanwille Apart from the unfathomable transgression of not finishing this in ruby, do you think this would be a smart idea? Because if I were to produce an erb version of the game, I might as well scrap the whole backend thing entirely, without having to wonder about JS injections, when the whole game itself could be essentially written in JS... ;)

**Comment by stefanwille** [comment]
Having everything in JavaScript is great, and having it as AngularJS app is also great. However I believe that building the game in the terminal is challenging enough already... 

I recommend that you the game in Ruby first. Once you figured that out, you can still build a JavaScript+Angular version. The difficulty is not in typing in the actual source code, but in wrapping your head around the process and turning that into code. Switching to another language should be comparatively easy.

**Comment by supernoir** [comment]
That was the plan :)
